name: Build and Deploy
on:
  push:
    branches:
      - main #thay vì "main" có thể dùng là tên branch của bạn
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Angular Application
        run: npm run build --prod
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/app-share-movies/
